version: 2
jobs:
  build:
    working_directory: ~/taapProject
    docker:
      # Android the primary container
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx6400m
      _JAVA_OPTIONS: "-Xmx1G"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - run:
          name: List Paths
          command: ls -lagh && cd TAAP/ && ls -lagh
      - restore_cache:
          key: jars-{{ checksum "TAAP/build.gradle" }}-{{ checksum  "TAAP/app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: cd TAAP && ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/taapProject/TAAP/.gradle
          key: jars-{{ checksum "TAAP/build.gradle" }}-{{ checksum  "TAAP/app/build.gradle" }}
      - run:
          name: Build Debug
          command: cd TAAP && ./gradlew assembleDebug
      - run:
          name: Build Release
          command: cd TAAP && ./gradlew assembleRelease
      - run:
          name: Run Tests
          command: cd TAAP && ./gradlew test --debug
      - store_artifacts:
          path: TAAP/app/build/reports
          destination: reports
      - store_test_results:
          path: TAAP/app/build/test-results